name: Android CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'adopt'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew clean build
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: apks
        path: androidApp/build/outputs/apk/release/*.apk
    - name: Download a Build Artifact
      uses: actions/download-artifact@v4.1.8
      with:
        name: apks
        path: ${{ github.workspace }}/androidApp/build/outputs/apk/release
          
